### ISSUE TITLE
No support for Laravel 5

### ISSUE THREAD

**Issue by rex** [Vinelab/iTunes#3]
Just tried installing via composer ( `"vinelab/itunes": "dev-master",`), but get the following output. Just FYI. It would be much more convenient for incoming developers like myself if there was a notice in the readme that indicated Laravel 5 was unsupported.

```
^@Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.0.28
    - Conclusion: don't install laravel/framework v5.0.28
    - Conclusion: don't install laravel/framework v5.0.27
    - Conclusion: don't install laravel/framework v5.0.26
    - Conclusion: don't install laravel/framework v5.0.25
    - Conclusion: don't install laravel/framework v5.0.24
    - Conclusion: don't install laravel/framework v5.0.23
    - Conclusion: don't install laravel/framework v5.0.22
    - Conclusion: don't install laravel/framework v5.0.21
    - Conclusion: don't install laravel/framework v5.0.20
    - Conclusion: don't install laravel/framework v5.0.19
    - Conclusion: don't install laravel/framework v5.0.18
    - Conclusion: don't install laravel/framework v5.0.17
    - Conclusion: don't install laravel/framework v5.0.16
    - Conclusion: don't install laravel/framework v5.0.15
    - Conclusion: don't install laravel/framework v5.0.14
    - Conclusion: don't install laravel/framework v5.0.13
    - Conclusion: don't install laravel/framework v5.0.12
    - Conclusion: don't install laravel/framework v5.0.11
    - Conclusion: don't install laravel/framework v5.0.10
    - Conclusion: don't install laravel/framework v5.0.9
    - Conclusion: don't install laravel/framework v5.0.8
    - Conclusion: don't install laravel/framework v5.0.7
    - Conclusion: don't install laravel/framework v5.0.6
    - Conclusion: don't install laravel/framework v5.0.5
    - Conclusion: don't install laravel/framework v5.0.4
    - Conclusion: don't install laravel/framework v5.0.3
    - Installation request for vinelab/itunes dev-master -> satisfiable by vinelab/itunes[dev-master].
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - vinelab/itunes dev-master requires illuminate/cache 4.* -> satisfiable by illuminate/cache[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/cache v4.0.0|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.1|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.10|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.2|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.3|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.4|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.5|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.6|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.7|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.8|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.0.9|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.0|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.10|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.11|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.12|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.14|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.15|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.17|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.18|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.19|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.21|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.23|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.24|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.25|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.26|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.27|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.28|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.29|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.3|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.30|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.4|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.5|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.7|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.8|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.1.9|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.17|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/cache v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.18, v5.0.19, v5.0.2, v5.0.20, v5.0.21, v5.0.22, v5.0.23, v5.0.24, v5.0.25, v5.0.26, v5.0.27, v5.0.28, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].
```

**Comment by Mulkave** [comment]
@rex yes this hasn't been updated to support L5 yet, appreciate a PR if you can.

**Comment by jpmurray** [comment]
Any news on this?

**Comment by Mulkave** [comment]
Will give it a shot, if not tonight tomorrow max 😀

**Comment by rex** [comment]
@Mulkave I wish I had cycles to dedicate to this because I'd love to help! Let me know if you have any luck implementing Laravel 5 support :smile:

**Comment by jpmurray** [comment]
@Mulkave if you need any testing, do not hesitate to ping! ;-)

**Comment by jpmurray** [comment]
I went on and tried to play a little with the code, and there is also a problem of dependencies coming from vinelab/http at which point I decided that it was maybe a little too deep for me to spend more time in it, so I'll be just waiting if you have time to update (because frankly, your caching feature makes it worthwhile!).

**Comment by Mulkave** [comment]
hey guys, just given it a shot in the https://github.com/Vinelab/iTunes/tree/l5 branch so please try it out and let me know how it goes so that I merge and update docs.

You can do that by lowering your `minimum-stability` to `dev` and requiring `"vinelab/itunes": "dev-l5"`

**Comment by jpmurray** [comment]
@Mulkave : I just installed l5 branch perfectly. I'll test if everything works with Laravel in the coming hours.

**Comment by jpmurray** [comment]
@Mulkave I'm getting a `ConfigurationException in Agent.php line 238: Incomplete Configuration` error. Here is the complete output.

    in Agent.php line 238
    at Agent->request('search', array('term' => 'Metallica')) in Agent.php line 81
    at Agent->search('Metallica') in Facade.php line 210
    at Facade::__callStatic('search', array('Metallica')) in routes.php line 34
    at Agent::search('Metallica') in routes.php line 34
    at RouteServiceProvider->{closure}()
    at call_user_func_array(object(Closure), array()) in Route.php line 155
    at Route->runCallable(object(Request)) in Route.php line 130
    at Route->run(object(Request)) in Router.php line 704
    at Router->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
    at Pipeline->then(object(Closure)) in Router.php line 706
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 671
    at Router->dispatchToRoute(object(Request)) in Router.php line 631
    at Router->dispatch(object(Request)) in Kernel.php line 237
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
    at VerifyCsrfToken->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 54
    at ShareErrorsFromSession->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
    at StartSession->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
    at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
    at EncryptCookies->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 42
    at CheckForMaintenanceMode->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
    at Pipeline->then(object(Closure)) in Kernel.php line 123
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 88
    at Kernel->handle(object(Request)) in index.php line 54

**Comment by Mulkave** [comment]
@jpmurray you're gonna need a `php artisan vendor:publish` after installation

**Comment by jpmurray** [comment]
@Mulkave well, now I'm not an undercover Laravel student anymore ;-) Ok, so in `php artisan tinker` calling for `ITunes::search('Metallica')` will yield results! Although trying to use it in a controller will get me a class not found error.

I tried adding an aliases to `config/app.php` with no avail. Honestly, it's my first time using a custom package in Laravel, and I'm a bit lost. I thought that if it worked with tinker it should be all set for controllers, what am I doing wrong in your opinion?

**Comment by Mulkave** [comment]
@jpmurray totally fine mate, thanks for trying. Will check it out on my side and try to reproduce the issue and will get back to you on it.

**Comment by jpmurray** [comment]
@Mulkave nevermind, I wasn't using the right depedency name. Here's what I did, and everything works fine:

- Install via composer;
- Add `Vinelab\ITunes\ITunesServiceProvider::class,` to the provider array in `config/app.php`
- Add `'ITunes' => Vinelab\ITunes\Facades\Agent::class, ` to the aliases array in `config/app.php`
- In my controller add `use ITunes;` to the beggining of the file (I was using `Vinelab\ITunes` before, that's what didn't worked!)

And then, using `$test = ITunes::search('Metallica');` in my controller works perfectly fine!

**Comment by Mulkave** [comment]
@jpmurray awesome! Seems like this bit of code in the service provider that used to auto-alias the class doesn't work anymore.

```php
$this->app->booting(function () {

        $loader = \Illuminate\Foundation\AliasLoader::getInstance();
        $loader->alias('ITunes', 'Vinelab\ITunes\Facades\Agent');
});
```

**Comment by jpmurray** [comment]
@Mulkave it would appear so, commenting it out won't impact the results anywhere.

**Comment by Mulkave** [comment]
@jpmurray hmmm weird, I just tried it with the latest **l5** version and it worked without manually aliasing the class, here's my controller code:

```php
<?php

namespace App\Http\Controllers;

use ITunes;

class AController extends Controller
{
    public function check()
    {
        return ITunes::search('Metallica');
    }
}

```

Can you please try a `composer update` then removing the alias from your config? I know it's silly not so major but am just curious :smile:

**Comment by jpmurray** [comment]
@Mulkave sure thing, I'd ask the same ;-) So I'm getting an exception:

`ErrorException in Agent.php line 41:
Argument 2 passed to Vinelab\ITunes\Agent::__construct() must be an instance of Vinelab\Http\Client, instance of Illuminate\Cache\CacheManager given, called in /home/vagrant/Code/joornal/vendor/vinelab/itunes/src/Vinelab/ITunes/ITunesServiceProvider.php on line 36 and defined`

**Comment by Mulkave** [comment]
@jpmurray yep that's true, weird error though. Can you please make sure of the commit ID in your `composer.lock` file? by looking near `vinelab/itunes` the reference should be 88c926989ce00ff49e09772ebb08bdae23fbf5f0

**Comment by jpmurray** [comment]
@Mulkave Yep, it's good. I'll look into my code, maybe I made a mistake somewhere, because I honestly can't see any changes from when it was working. I'll be back with that in a few moments.

**Comment by jpmurray** [comment]
@Mulkave yeah, so I reset my local developpement branch and started all from scratch, now it works. Go figure! ;-)

I guess congratulations are in order, your packages have 5.1 LTS support ! ;-)

**Comment by Mulkave** [comment]
yep, that's awesome :smile: thanks for the constant feedback @jpmurray, merging into master now!

**Comment by jpmurray** [comment]
Thanks to you for thoses updates!
